feat(PLAT-4): adding freud-icon lib listing in storybook
Zenklub/freud-ds pull request #77
Opened 2023-04-11 22:10 UTC by kayran

Adding icon list view with search and clipboard copy:

https://user-images.githubusercontent.com/474481/231293641-0f078e31-424f-4b68-8392-25da729c547b.mp4

2023-04-12 01:55 UTC, jeanbispo requested changes

2023-04-12 01:55 UTC, jeanbispo commented on packages/web/stories/icons/icon-class/all-icons/all-icons.component.ts
> +    console.log(iconNamesJson);
remove console.log

2023-04-12 01:55 UTC, jeanbispo commented on packages/web/stories/icons/icon-class/all-icons/all-icons.component.ts
> +    console.log(this.message);
remove console.log

2023-04-12 01:55 UTC, jeanbispo commented on packages/web/stories/icons/icon-class/all-icons/all-icons.component.ts
> +  // constructor(private clipboardService: ClipboardService, private messageService: FreudMessageService) {}
remove commented line

2023-06-23 17:02 UTC, kayran commented on packages/web/stories/icons/icon-class/all-icons/all-icons.component.ts
> +    console.log(iconNamesJson);
```suggestion
```

2023-06-23 17:03 UTC, kayran commented on packages/web/stories/icons/icon-class/all-icons/all-icons.component.ts
> +  // constructor(private clipboardService: ClipboardService, private messageService: FreudMessageService) {}
```suggestion
```

2023-06-23 17:03 UTC, kayran commented on packages/web/stories/icons/icon-class/all-icons/all-icons.component.ts
> +    console.log(this.message);
```suggestion
```

2023-06-23 17:09 UTC, jeanbispo approved these changes

2023-06-23 17:10 UTC, merged