feat(TSAU-1590): clickable toast
Zenklub/freud-ds pull request #95
Opened 2023-09-18 19:52 UTC by ramon-ferreira

Add changes to `feedback/toast/toast.component.scss` component:

- Now has the URL string prop tha makes the toast clickable
- Added examples to component Story

2023-09-18 21:26 UTC, andreseiji requested changes

2023-09-18 21:26 UTC, andreseiji commented on package-lock.json
Esse arquivo de _lockfile_ não deveria ter tantas alterações.

Usar o Node 16 com o comando `npm i --legacy-peer-deps`, conforme está no README.md

2023-09-18 21:26 UTC, andreseiji commented on packages/web/package-lock.json
Esse arquivo de _lockfile_ não deveria ter tantas alterações.

Usar o Node 16 com o comando `npm i --legacy-peer-deps`, conforme está no README.md

2023-09-18 21:26 UTC, andreseiji commented on packages/web/angular.json
> +    "analytics": "06f5102b-1073-4a0f-93f3-b0833f2253e0"
@ramon-ferreira Para a funcionalidade, precisamos desse ID do analytics? Me parece uma mudança não relacionada.

2023-09-18 21:26 UTC, andreseiji commented on packages/web/projects/web-components/src/components/feedback/toast/toast.component.scss
> +    &:hover {
Esse estilo com esse seletor CSS parece não alterar nada. Pelo que vi aqui, o `background-color` fica na `div` que tem a classe `.p-toast-message`. Seria bom validar com design também aqui se for ter um novo estilo para o hover.

2023-09-18 21:26 UTC, andreseiji commented on packages/web/projects/web-components/src/components/feedback/toast/toast.component.ts
> +  @Input() url!: string;
Por que o uso do _non-null assertion operator_ aqui?

2023-09-18 21:26 UTC, andreseiji commented on packages/web/projects/web-components/src/components/feedback/toast/toast.component.ts
> +    <p-toast [position]="position" [key]="key" [class.clickable] = "url" (click)="openURL($event)"></p-toast>
Sugestão: para os casos em que não precise de um toast clicável, podemos usar um _noop_, ao invés de sempre chamar o método que fará as verificações.

Sugestão _(code style)_:
`[class.clickable] = "url"` -> `[class.clickable]="url"` (sem os espaços)

2023-09-18 21:26 UTC, andreseiji commented on packages/web/projects/web-components/src/components/feedback/toast/toast.component.ts
> +    if(!isCloseBtn && this.url){
Sugestão _(code style)_:
```suggestion
if (!isCloseBtn && this.url) {
```

2023-09-18 21:26 UTC, andreseiji commented on packages/web/projects/web-components/src/components/feedback/toast/toast.component.ts
> +      window.open(this.url, '_blank');
Aqui sempre vamos querer que seja aberto em outra aba? Ou o `target` pode variar?

2023-09-19 12:52 UTC, ramon-ferreira commented on packages/web/package-lock.json
Não, foi um install normal, vou corrigir isso.

2023-09-19 13:57 UTC, ramon-ferreira commented on packages/web/projects/web-components/src/components/feedback/toast/toast.component.ts
> +    if(!isCloseBtn && this.url){
Feito

2023-09-19 21:11 UTC, andreseiji commented on packages/web/projects/web-components/src/components/feedback/toast/toast.component.ts
> +    const whereToOpen = this.openInNewTab ? '_blank' : '_top';
@ramon-ferreira o padrão se não for abrir em uma nova aba é `_self`.

2023-09-19 21:52 UTC, ramon-ferreira commented on packages/web/projects/web-components/src/components/feedback/toast/toast.component.ts
> +    const whereToOpen = this.openInNewTab ? '_blank' : '_top';
Não usei _self porque no exemplo fica dentro de um iframe, daí não abriria na página certinho e sim dentro do iframe. Mas agora como parâmetro ficou melhor, obrigado pela sugestão!

2023-09-20 13:53 UTC, andreseiji approved these changes

2023-09-22 13:39 UTC, merged